repos:
  - repo: local
    hooks:
      - id: check-markdown
        name: Check Markdown
        entry: bash -c 'check=staged-changes ./scripts/githooks/check-markdown-format.sh'
        language: system
        pass_filenames: false
